name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
author: Maxim Vatentsov <admin@gtn-craft.ru>
version: ${project.version}
load: STARTUP

permissions:
    worldrestriction.bypass:
        description: Allow bypass worldrestriction.
        default: op
